### ISSUE TITLE
Storyboard?

### ISSUE THREAD

**Issue by daviddelmonte** [dillidon/Alerts-Pickers#1]
This is a superb control! Perhaps you could add an example using a Storyboard? I have a large project, where Alerts-Pickers would need to be incorporated.

**Comment by dillidon** [comment]
@daviddelmonte yes, you can. But you have to know the height of your viewController. If you use autolayout you can add property, which will catch the lowest point in ‘viewDidLayout’ method. I’ll add example using a Storyboard in a few days.

**Comment by daviddelmonte** [comment]
Many thanks!

**Comment by dillidon** [comment]
@daviddelmonte add [ColorPicker](https://github.com/dillidon/Alerts-Pickers#colorpicker) using a Storyboard with Autolayout.
