### ISSUE TITLE
Error: init(coder:) has not been implemented"

### ISSUE THREAD

**Issue by kentonraiford** [dillidon/Alerts-Pickers#12]
App works fine when this is in app delegate: 
window?.rootViewController = UINavigationController(rootViewController: ViewController())

When it's not and I try to present it, I get these errors:

1) Fatal error: init(coder:) has not been implemented

2) Warning: Attempt to present <UIAlertController: 0x108839200> on <MainVC: 0x105055e00> whose view is not in the window hierarchy!

**Comment by kentonraiford** [comment]
I think it's coming from here, but I'm not sure:

`public func show(animated: Bool = true, vibrate: Bool = false, completion: (() -> Void)? = nil) {
        DispatchQueue.main.async {
            UIApplication.shared.keyWindow?.rootViewController?.present(self, animated: animated, completion: completion)
            if vibrate {
                AudioServicesPlayAlertSound(kSystemSoundID_Vibrate)
            }
        }
    }`

**Comment by dillidon** [comment]
@kentonraiford do you use storyboards?

**Comment by kentonraiford** [comment]
@dillidon Thanks for the quick reply! 

I am using storyboards and I am trying to set the tableView = to the tableView in my UIViewController, because I don't want the tableView to take up the entire view.


----------
I figured out a way around my earlier problem. Here is the code I implemented:

func presentAlert(alertToDisplay: UIAlertController)
    {
        let alertWindow = UIWindow(frame: UIScreen.main.bounds)
        alertWindow.rootViewController = UIViewController()
        alertWindow.windowLevel = UIWindowLevelAlert + 1;
        alertWindow.makeKeyAndVisible()
        alertWindow.rootViewController?.present(alertToDisplay, animated: true, completion: nil)
    }

**Comment by dillidon** [comment]
@kentonraiford its simple, as you think. Take a look at the example with Color Picker
