### ISSUE TITLE
Reasons for minimum target iOS 11?

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [dillidon/Alerts-Pickers#14]
Hello, Thanks for this Marvelous library.

Can you tell the reason, why we require to set minimum target to iOS 11?

And, the Alert/ActionSheet are default one? with modified?

**Comment by dillidon** [comment]
@Rashesh-Bosamiya because ios 10 installed on 65%, about 40% is ios 11, so while you make your app this 40% will rise and differences in code between ios 10 & 11 is minimal

**Comment by cerupcat** [comment]
I'd like to know this as well. Are there APIs specific to iOS 11 being used?

**Comment by cerupcat** [comment]
@Rashesh-Bosamiya  Looking closer, there are specific iOS 11 calls in many of the classes.
