### ISSUE TITLE
[Request]UIView

### ISSUE THREAD

**Issue by Nathan961207** [dillidon/Alerts-Pickers#27]
Hi, is it possible to implement a custom UIView that is empty?

**Comment by dillidon** [comment]
@Nathan961207 example? for what?

**Comment by Nathan961207** [comment]
An example on how to add a custom UIView to be a container for other UI
elements.

For example three UITextField and one UITextView in one UIView using your
code.

I prefer to not modify any of your code that’s why I’m asking you.

**Comment by Nathan961207** [comment]
Sorry for wasting your time, I did not see this section.

https://github.com/dillidon/alerts-and-pickers#set-content-viewcontroller
