### ISSUE TITLE
Issue with VerticalScrollFlowLayout

### ISSUE THREAD

**Issue by surjeet-singh** [dillidon/Alerts-Pickers#29]
Hi, 
I am using 'VegaScrollFlowLayout' class to add animation to collectionView items. This works like a charm if I use a fixed itemSize for CollectionView cell with no section header. But If I use any (section header or dynamic itemSize). The CollectionView displayed item with some weird way.
I face these 2 issues while using this class:

1. When adding section header, and use default FlowLayout. Everything works well. When using 'VerticalScrollFlowLayout', Section Header doesn't display anymore.

2. If use 'estimatedItemSize' instead of 'itemSize' for dynamic item size. The animation doesn't work properly.
Let me know If you can help me on this.
Thanks

**Comment by dillidon** [comment]
@surjeet-singh I took `VegaScrollFlowLayout` from [VegaScroll](https://github.com/ApplikeySolutions/VegaScroll) as you can see. Unfortunately this flowLayout doesnt work with section headers and dynamic item size, only with fixed item size.

**Comment by surjeet-singh** [comment]
I am closing this issue, As it related to [VegaScroll](https://github.com/ApplikeySolutions/VegaScroll). I have posted same [issue to VegaScroll](https://github.com/ApplikeySolutions/VegaScroll/issues/17).
