### ISSUE TITLE
How to remove unnecessary permissions

### ISSUE THREAD

**Issue by PedroCavaleiro** [dillidon/Alerts-Pickers#43]
I've tried to upload my app to the app store to start the TestFlight and it got rejected and got this message

> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

I figure that your library has some calls to these functionalities since I do not use them. Is there a way to fix it, I do not want to request this access to my users

**Comment by hardikamal** [comment]
@PedroCavaleiro Any solution to this?

**Comment by PedroCavaleiro** [comment]
You have two solutions, add the permissions to the Info.plist, the permissions are made on demand, or comment the whole classes that you don’t need
I ended up commenting the whole classes that I didn’t need, it’s not the ideal solution.
As long as they’re there it does not matter if you use them or not, Apple will still see them and reject the app if said permissions are not in the Info.plist

**Comment by hardikamal** [comment]
Ok, thanks. My app got rejected. Have added the permission in Info.plist and now resubmitting it.
